# Generated by Django 4.2.7 on 2023-12-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicianModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=56)),
                ('lastName', models.CharField(max_length=56)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=18)),
                ('instrumentType', models.CharField(max_length=56)),
            ],
        ),
    ]
